# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - tipjar2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install
      working-directory: tipjar

      - name: Find first WAR file and rename it to ROOT
      run: mv `find ${{ github.workspace }}/tipjar/target/*.war | head -n 1` ${{ github.workspace }}/tipjar/target/ROOT.war 

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tipjar2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8bd548f0845d45f087b00936b2c93a24 }}
        package: '${{ github.workspace }}/tipjar/target/*.war'